- type: entity
  name: станбатон контрактора
  parent: BaseItem
  id: SichContractorStunbaton
  description: Унікальний станбатон виробництва GoldenEye, який створений задля швидкого обеззброєння та захоплення цілі.
  components:
  - type: Sprite
    sprite: _Sich/Objects/Weapons/Melee/contractor_stunbaton.rsi
    layers:
    - state: stunbaton_off
      map: [ "enum.ToggleableVisuals.Layer" ]
  - type: Stunbaton
    energyPerUse: 50
  - type: ItemToggle
    predictable: false
    soundActivate:
      collection: sparks
      params:
        variation: 0.250
    soundDeactivate:
      collection: sparks
      params:
        variation: 0.250
    soundFailToActivate:
      path: /Audio/Machines/button.ogg
      params:
        variation: 0.250
  - type: ItemToggleMeleeWeapon
    activatedDamage:
      types:
        Blunt: 0
  - type: MeleeWeapon
    wideAnimationRotation: -135
    damage:
      types:
        Blunt: 4
    bluntStaminaDamageFactor: 5.0
    angle: 70
    animation: WeaponArcSlash
  - type: StaminaDamageOnHit
    damage: 55
    sound: /Audio/Weapons/egloves.ogg
  - type: StaminaDamageOnCollide
    damage: 55
    sound: /Audio/Weapons/egloves.ogg
  - type: Battery
    maxCharge: 10000
    startingCharge: 10000
  - type: UseDelay
  - type: Item
    heldPrefix: off
    size: Normal
  - type: Clothing
    sprite: _Sich/Objects/Weapons/Melee/contractor_stunbaton.rsi
    quickEquip: false
    slots:
    - Belt
  - type: DisarmMalus
    malus: 0.225
  - type: Appearance
  - type: GenericVisualizer
    visuals:
     enum.ToggleableVisuals.Enabled:
        enum.ToggleableVisuals.Layer:
          True: {state: stunbaton_on}
          False: {state: stunbaton_off}
  - type: StaticPrice
    price: 80
  - type: Riggable
  - type: SolutionContainerManager
    solutions:
      battery:
        maxVol: 5
  - type: InjectableSolution
    solution: battery
  - type: DrawableSolution
    solution: battery
